
var wordsRaw = [
    "!!Exclamation (oop)",
    "Yes", "sytoop",
    "no", "snoop",
    "hello", "sloop",
    "thank you", "stoop",
    "sorry", "sroop",
    "bye", "sboop",
    "wow", "soboop",
    "uh oh (oops)", "suboop",
    "oh (understand)", "sutoop",

    "!!Pronoun (ip)",
    "i", "skip",
    "we", "skipity",
    "you", "sklip",
    "you all", "sklipity",
    "he", "sklipip",
    "she", "sklipip",
    "they", "sklipipity",
    "!Interrogative (sclu)",
    "who", "sclupip",
    "what", "sclufip",
    "where", "scludip",
    "when", "sclutip",
    "why", "sclurip",
    "how", "sclumip",
    "which", "sclupapip",
    "whose", "sclunip",
    "!Indefinite (sclo)",
    "someone", "sclosopip",
    "somewhere", "sclosodip",
    "some way", "sclosomip",
    "something", "sclosofip",
    "sometime", "sclosotip",
    "some reason", "sclosorip",
    "nobody", "sclonopip",
    "nowhere", "sclonodip",
    "no way", "sclonomip",
    "nothing", "sclonofip",
    "never", "sclonotip",
    "no reason", "sclonorip",
    "anybody", "sclodopip",
    "anywhere", "sclododip",
    "any way", "sclodomip",
    "anything", "sclodofip",
    "any time", "sclodotip",
    "any reason", "sclodorip",
    "everybody", "sclobopip",
    "everywhere", "sclobodip",
    "every way", "sclobomip",
    "everything", "sclobofip",
    "everytime", "sclobotip",
    "every reason", "scloborip",
    "that person", "scloropip",
    "there", "sclorodip",
    "that method", "scloromip",
    "that", "sclorofip",
    "then", "sclorotip",
    "that reason", "sclororip",
    "this person", "sclotopip",
    "here", "sclotodip",
    "this method", "sclotomip",
    "this", "sclotofip",
    "now", "sclototip",
    "this reason", "sclotorip",

    "!!Verb",
    "!Basic",
    "is", "se",
    "let", "skle",
    "use", "ske",
    "place", "ske",
    "dye", "ske",
    "know", "sote",
    "become", "same",
    "like", "sade",
    "see", "seme",
    "can", "sme",
    "may", "sne",
    "exist", "sto",

    "!Inventory (slo)",
    "have", "slote",
    "own", "slote",
    "need", "slode",
    "want", "slode",
    "pick up", "slope",
    "collect", "slope",
    "throw out (give)", "slore",
    "give", "slore",
    "store", "slobe",
    "lose", "slobipe",
    "misplace", "slobipe",
    "hold", "sloye",
    "put", "slotupe",
    "keep", "slome",

    "!Attempt Actions (sy)",
    "do", "syme",
    "achieve", "sytipe",
    "win", "syripe",
    "lose", "syre",
    "fail", "syre",
    "try", "sye",
    "give up", "syte",
    "allow", "sybe",
    "work", "syrite",
    "start", "sytope",
    "stop", "sytape",
    "happen", "symape",
    "continue", "symade",
    "decide", "sytode",
    "!Movement (sbi)",
    "go", "sbile",
    "stand", "sbime",
    "push", "sbibepe",
    "fall", "sbide",
    "fly", "sbiste",
    "jump", "sbite",
    "walk", "sbibe",
    "run", "sibepe",
    "crouch", "sbifte",
    "crawl", "sbispe",
    "swim", "sbifte",
    "climb", "sbistepe",
    "open", "sbishe",
    "close", "sbishepe",
    "turn", "sbidepe",
    "look", "sbirepe",
    "ride", "sbiple",

    "!Social (spl)",
    "say", "splode",
    "write", "splode",
    "ask", "splade",
    "sleep", "sle",
    "leave", "sple",
    "disconnect", "sple",
    "join", "splipe",
    "command", "splome",
    "help", "splare",
    "show", "splore",
    "play", "splope",
    "live", "splote",
    "meet", "splorepe",
    "follow", "splire",
    "offer", "splite",
    "lie", "splide",
    "trade", "splitre",
    "buy", "splibe",
    "sell", "splishe",

    "!Item (sli)",
    "craft", "sline",
    "find", "slimbe",
    "pick up", "slipe",
    "break", "slipe",
    "brew", "slite",
    "enchant", "slime",
    "farm", "slite",
    "summon", "slibipe",
    "smelt", "slile",
    "breed", "slibepe",
    "lead", "slibe",
    "activate", "slire",
    "require", "sliste",
    "fish", "slibide",

    "!Combat (sbo)",
    "kill", "sbole",
    "die", "sbolepe",
    "steal", "sbope",
    "hit", "sboleme",
    "shoot", "sbolede",
    "wear", "sbosole",
    "respawn", "sbolipe",
    "explode", "sbosplode",
    "burn", "sbofire",
    "mine", "sbolipe",

    "!!Adverbs (up)",
    "!Basic",
    "already", "sdonup",
    "also", "sdup",
    "always", "slodup",
    "defiantly", "solodup",
    "deliberately", "sousup",
    "eventually", "slatup",
    "exactly", "sperdup",
    "frequently", "slydup",
    "instead", "sinstup",
    "never", "sladup",
    "not", "snup",
    "often", "slidup",
    "only", "sonup",
    "out", "soutup",
    "poorly", "sadabup",
    "probably", "sprobup",
    "quickly", "saftup",
    "really", "srelup",
    "slowly", "solerodup",
    "so (very)", "stup",
    "sometimes", "sludup",
    "together", "stotup",
    "too", "sodup",
    "up", "sup",

    "!!Conjunctions (eep)",
    "!Coordinating (sl)",
    "and", "sleep",
    "but", "slpeep",
    "for", "sleteep",
    "nor", "slareep",
    "or", "sloreep",
    "so", "slateep",
    "yet", "slapeep",

    "!Subordinating (sp)",
    "while", "spledeep",
    "though", "spleteep",
    "although", "splateep",
    "if", "spleep",
    "unless", "spapeep",
    "until", "splareep",
    "than", "splatreep",
    "rather than", "splotreep",
    "whether", "splotheep",
    "after", "splayeep",
    "before", "sployeep",
    "since", "spliyeep",
    "once", "spleyeep",
    "when", "spluyeep",
    "whenever", "spluyipeep",
    "because", "speep",
    "why", "spapeep",
    "that", "spreep",
    "whatever", "sprapeep",
    "which", "spropeep",
    "who", "sprupeep",
    "whoever", "spripeep",
    "how", "sprateep",
    "where", "sproteep",
    "wherever", "spriteep",

    "!Correlative Conjunctions (sr)",
    "as .. as", "sreep .. sreep",

    "!!Preposition (ap)",
    "!Basic",
    "preposition", "sap",
    "about", "sclap",
    "above", "sclatap",
    "across", "sclotap",
    "after", "sclitap",
    "against", "sclutap",
    "along", "sclytap",
    "among", "scladap",
    "around", "sclidap",
    "as", "sclodap",
    "at", "sclydap",
    "atop", "scledap",
    "before", "sclepap",
    "behind", "sclopap",
    "below", "sclapap",
    "between", "sclipap",
    "but", "sclypap",
    "by", "sclerap",
    "despite", "sclirap",
    "down", "sclyrap",
    "during", "sclarap",
    "following", "sclorap",
    "for", "sclafap",
    "from", "sclefap",
    "except", "sclifap",
    "in", "slap",
    "including", "sclofap",
    "inside", "sclufap",
    "instead of", "sclyfap",
    "into", "sclacap",
    "like", "sclecap",
    "near", "sclicap",
    "next to", "sclocap",
    "of", "sclucap",
    "off", "sclycap",
    "on", "sclap",
    "opposite", "scarap",
    "out", "scerap",
    "outside", "scirap",
    "over", "scorap",
    "past", "scurap",
    "since", "scyrap",
    "than", "scatap",
    "through", "scetap",
    "to", "srap",
    "towards", "scitap",
    "under", "scotap",
    "up", "stap",
    "versus", "scutap",
    "via", "scytap",
    "with", "scidap",
    "without", "scodap",

    "!!Determiner (yp)",
    "!Basic",
    "the", "syp",
    "a", "slyp",
    "this", "smyp(ity)",
    "that", "snyp(ity)",
    "a few", "smapyp",
    "a lot", "smopyp",
    "any", "smypyp",
    "some", "smipyp",
    "most", "smupyp",
    "enough", "smepyp",
    "all", "stepyp",
    "both", "stepyp",
    "either", "scryp",
    "neither", "scrapyp",
    "each", "scrotyp",
    "every", "scratyp",
    "other", "scridyp",
    "another", "scrodyp",
    "quite (such)", "smachoyp",
    "more", "stopyp",
    "less", "stipyp",
    "!Possessive",
    "my", "skyp",
    "our", "skypity",
    "your", "sklyp",
    "your", "sklypity",
    "his", "sklipyp",
    "her", "sklipyp",
    "their", "sklipypity",

    "!!Adjective (op)",
    "!Basic",
    "adjective", "sop",
    "like", "sop",
    "anti", "stlop",

    "!Color (spi)",
    "light", "spilop",
    "dark", "spidop",
    "red", "spirop",
    "yellow", "spilop",
    "green", "spidop",
    "black", "spiblop",
    "brown", "slibrop",
    "blue", "spicop",
    "white", "spitrop",
    "orange", "spiranop",
    "magenta", "spimatop",
    "gray", "spiratop",
    "cyan", "spicanop",
    "purple", "spipurop",

    "!Basic",
    "cooked (baked)", "sitop",
    "raw", "sititop",
    "mossy", "simop",
    "smooth (polished)", "sisop",
    "chiseled", "sichosop",
    "cracked", "sicrosop",
    "full", "sifop",
    "empty", "stlop sifop",
    "hungry", "stlop sifop",
    "infested", "silopop",
    "automatic", "silopop",
    "semi-automatic", "smupyp silopop",

    "!Game related (sti)",
    "common", "stitop",
    "natural", "stidop",
    "dead", "stidipop",
    "alive", "stidopop",
    "hard (difficulty)", "stidimop",
    "medium (difficulty)", "stidomop",
    "easy (difficulty)", "stidumop",
    "op", "stiritop",

    "!Concepts (stri)",
    "right", "stritop",
    "left", "stlop stritop",
    "new", "stritotop",
    "old", "stlop strotop",
    "good", "stritatop",
    "bad", "stlop stritatop",
    "tall", "stridatop",
    "short", "stlop stridatop",
    "large", "strilotop",
    "small", "stlop strilotop",
    "different", "strimadop",
    "same", "stlop strimadop",
    "important", "stritarop",
    "public", "stripamop",
    "private", "stlop stripamop",
    "entire", "strilarop",
    "only", "strilatop",
    "early", "strimolop",
    "late", "stlop strimolop",
    "true", "strilomop",
    "false", "stlop strilomop",
    "opaque", "stripatop",
    "clear", "stlop stripatop",
    "recent", "stridimop",
    "better", "stritilop",
    "worse", "stlop stritilop",

    "!!Noun (ip)",
    "!Basic",
    "noun", "sip",
    "block", "slip",
    "item", "slikip",
    "entity", "slentip",

    "!Category (sa)",
    "arthropod", "sasbiarip",
    "mob", "sasbip",
    "player", "sasblapip",
    "npc", "sasblatip",
    "animal", "sasbepip",
    "food", "sastipip",
    "meat", "saslibsbetip",
    "dye", "saspip",
    "decoration", "sadecip",
    "storage", "sastorip",
    "mob loot", "saslibip",
    "potion", "saslutip",
    "spawn egg", "saslytip",
    "tool", "sasotoolip",
    "head", "sasblapip slibip",
    "biome", "saskolip",
    "bird", "safianip",
    "fruit", "sfrutip",
    "fuel", "safulip",
    "generated structure", "saskatip",

    "!Gameplay (sci)",
    "inventory", "scintip",
    "hand", "scinihip",
    "hunger", "scinhunip",
    "durability", "scidurip",
    "distance", "scidistip",
    "time", "scitimip",
    "xp", "scickspip",
    "crash", "scirasip",
    "name", "scinamip",
    "power", "scipobip",
    "treasure", "scitraship",

    "!F3 (scif)",
    "x", "scificksip",
    "y", "scifeyesip",
    "z", "scifseetip",
    "fps", "scifpeyesip",
    "hud", "scifeshudip",
    "chunk", "scifitip",
    "position", "scifiposip",
    "coordinates", "scifiposip",
    "light", "scifilitip",
    "north", "scifonortip",
    "south", "stlop scifonortip",
    "west", "scifobestip",
    "east", "stlop scifobestip",

    "!Technical (scit)",
    "screenshot", "scritshotip",
    "lan", "scritaretip",
    "server", "sciterbip",
    "bug", "scitubip",
    "version", "scitersip",
    "controls", "scitolip",
    "border", "scitordip",
    "spawn point", "scitspodip",
    "tick", "scitickip",
    "shaders", "scitaderip",
    "skin", "scitinip",
    "sound", "scitoundip",
    "mod", "scitodip",

    "!Gamemode (scir)",
    "buffet", "scirustomip",
    "superflat", "sciroflip",
    "amplified", "stlop sciroflip",
    "cheats", "sciribip",
    "creative", "sciratibip",
    "survival", "stlop sciratibip",
    "adventure", "scirenturip",
    "spectator", "scirectip",
    "hardcore", "scirardcip",
    "singleplayer", "scirosolip",
    "multiplayer", "stlop scirosolip",

    "!Server (scil)",
    "friend", "scilip",
    "currency", "scilicip",
    "quest", "scilickip",
    "mana", "scilimip",
    "lobby", "scililip",
    "tutorial", "scilitip",
    "chat", "scilockip",
    "loot box", "scilalip",
    "realms", "scilorip",
    "team", "scilatip",
    "auction", "scilabip",
    "parkour", "scilapip",
    "combat", "scilocip",
    "minigame", "scilomip",
    "lobby", "scilolip",
    "noob", "scilonip",
    "rank", "scilarip",
    "admin", "sciladmip",

    "!Natural (scl)",
    "cloud", "sclitip",
    "sky", "sclotip",
    "rain", "sclorip",
    "snow", "sclirip",
    "lightning", "sclyrip",
    "void", "sclatip",
    "sun", "sclodip",
    "moon", "scladip",
    "weather", "sclurip",
    "stars", "sclirip",
    "day", "sclafip",
    "night", "sclofip",
    "world", "sclip",
    "world seed", "sclip statip",
    "surface", "sclobip",
    "underground", "sclabip",
    "cave", "sclibip",
    "ravine", "sclebip",
    "waterfall", "sclehip",
    "iceberg", "sclohip",
    "ice spike", "sclahip",
    "cluster (deposit)", "scloslip",
    "floating island", "sclihip",

    "!Structure (scla)",
    "house", "sclahip",
    "tower", "sclatip",
    "city", "sclacip",
    "shop", "sclasip",
    "farm", "sclafip",
    "pit", "sclapip",

    "!Biome (sko)",
    "forest", "skodip",
    "birch forest", "slkibop skodip",
    "mountain", "skodipip",
    "taiga", "slkidop skodip",
    "beach", "skocipip",
    "ocean", "skocopip",
    "deep", "skocapip",
    "warm", "skocupip",
    "lukewarm", "skocepip",
    "cold", "skocypip",
    "island", "skocitip",
    "plains", "skodopip",
    "desert", "skonip",
    "lake", "skocibip",
    "river", "skocobip",
    "dark forest", "slkidop skodip",
    "swamp", "skocabip",
    "jungle", "skocubip",
    "savanna", "slkicop skodip",
    "edge", "skorupip",
    "end", "skohupip",
    "nether", "skohapip",
    "overworld", "skohipip",
    "badlands", "skomip",

    "!Structure (ska)",
    "mineshaft", "skadipip",
    "stronghold", "skdopip",
    "fossil", "skadypip",
    "buried treasure", "skadupip",
    "ocean ruin", "skadapip",
    "shipwreck", "skarapip",
    "ocean monument", "skaropip",
    "desert pyramid", "skaripip",
    "igloo", "skarypip",
    "jungle pyramid", "skarepip",
    "pillager outpost", "skapipip",
    "swamp hut", "skapopip",
    "village", "skapypip",
    "woodland mansion", "skapupip",
    "dungeon", "skapepip",
    "well", "skadepip",
    "nether fortress", "skadipip",
    "end city", "skadopip",
    "end ship", "skadadip",

    "!Enchantment (ske)",
    "aqua affinity", "skedipip",
    "bane of the arthropods", "skedopip",
    "blast protection", "skedupip",
    "channeling", "skedepip",
    "curse of binding", "skedypip",
    "curse of vanishing", "skepipip",
    "depth strider", "sketitip",
    "efficiency", "skenip",
    "feather falling", "sketutip",
    "fire aspect", "sketatip",
    "fire protection", "sketytip",
    "flame", "sketetip",
    "fortune", "sketodip",
    "frost walker", "sketadip",
    "impaling", "sketidip",
    "infinity", "sketedip",
    "knockback", "sketudip",
    "looting", "sketydip",
    "loyalty", "skedotip",
    "luck of the sea", "skedatip",
    "lure", "skedutip",
    "mending", "skedytip",
    "multishot", "skedetip",
    "piercing", "skedotip",
    "power", "skedip",
    "protection", "skerip",
    "punch", "skenip",
    "quick charge", "skeparip",
    "respiration", "skepyrip",
    "riptide", "skepurip",
    "sharpness", "sketip",
    "silk touch", "skepip",
    "smite", "skeporip",
    "sweeping edge", "skeperip",
    "thorns", "skemip",
    "unbreaking", "skebip",

    "!Tool (so)",
    "pickaxe", "sopitip",
    "axe", "sospopip",
    "shovel", "sospip",
    "hoe", "sostip",
    "fishing rod", "soslibidip",
    "shears", "soship",
    "lead", "sosbepip",
    "compass", "sofonortip",
    "clock", "sotimip",
    "flint and steel", "sofrip",
    "saddle", "sosadip",

    "!Wood (slk)",
    "wooden", "slkistop",
    "oak", "slkipop",
    "birch", "slkibop",
    "spruce", "slkisop",
    "acacia", "slkicop",
    "dark oak", "slkidop",
    "jungle", "slkidgop",
    "crimson", "slkinop",
    "warped", "slkirnop",

    "!Spawn egg (sly)",
    "spawn egg", "mob type + slypip",

    "!mob loot (slib)",
    "drop", "slibip",
    "for example", "bone = spitip slibip",
    "spider eye", "slibitip",
    "rabbit hide", "sliborip",
    "rabbit foot", "slibarip",
    "turtle egg", "slibatip",
    "scute", "slibutip",

    "!Combat (sle)",
    "armor", "sletip",
    "boots", "sletotip",
    "chestplate", "sletutip",
    "helmet", "sletatip",
    "leggings", "sletetip",
    "shield", "sletarip",
    "bow", "slebarip",
    "crossbow", "sleborip",
    "sword", "sleburip",
    "trident", "slebudip",
    "totem of undying", "sletirip",
    "health", "sletamip",
    "protection", "sletyrip",
    "damage", "sletomip",

    "!Ore (sli)",
    "netherite", "slimpip",
    "ancient debris", "slimpypip",
    "diamond", "slimip",
    "chainmail", "slithip",
    "emerald", "slicip",
    "redstone", "slidip",
    "quartz", "slitip",
    "lapiz", "slilip",
    "gold", "slirip",
    "iron", "slifip",
    "coal (charcoal)", "sliromip",
    "stone", "slipip",
    "ore", "slitrip",
    "obsidian", "slispip",
    "ingot", "slindip",
    "nugget", "slinudip",

    "!Potion (slu)",
    "glass bottle", "slutip",
    "bottle o' enchanting", "sludip",
    "milk bucket", "sbecip slobucip",
    "water bottle", "spirotip slutip",
    "awkward potion", "stonip slutip",
    "mundane potion", "slutrip",
    "thick potion", "slifitip slutip",
    "dragons breath", "sludobip",
    "splash", "slupip",
    "lingering", "slurip",
    "regeneration", "slurotip",
    "swiftness", "slufonip",
    "fire resistance", "sluforip",
    "healing", "sluholip",
    "night vision", "slunobip",
    "strength", "slusotip",
    "leaping", "slulopip",
    "water breathing", "slubobip",
    "slow falling", "slusofip",
    "luck", "slulokip",
    "poison", "sluposip",
    "weakness", "sluronip",
    "slowness", "slusonip",
    "harming", "sluhomip",
    "decay", "sludocip",
    "turtle master", "slutomip",

    "!Misc (slo)",
    "leather", "slospip",
    "clay", "slostrip",
    "snow", "slotrip",
    "brick", "sitop slostrip",
    "eye of ender", "slodendip",
    "firework", "slofibip",
    "fire charge", "sloficip",
    "book", "slobip",
    "book and quill", "slobocip",
    "bucket", "slobucip",
    "paper", "slopapip",
    "heart of the sea", "slohasip",
    "flint", "slofip",
    "feather", "slofetip",
    "fermented spider eye", "slofesip",

    "!Wooden (spo)",
    "boat", "spodopip",
    "fence", "spofip",
    "fence gate", "spofidip",
    "stripped log", "sposolip",
    "wood", "sposobip",
    "log", "spolodip",
    "planks", "spolopip",
    "sign", "sposanip",
    "stick", "spostatip",
    "bowl", "spobolip",
    "door", "spodorip",
    "trapdoor", "spotodrip",

    "!Decor (spa)",
    "glass", "spadlip",
    "bed", "spabip",
    "terracotta", "spatip",
    "glazed terracotta", "sitp spatip",
    "wool", "spadip",
    "carpet", "spacirip",
    "concrete powder", "spacapip",
    "concrete", "spacip",
    "shulker box", "spasebip",
    "banner", "spabanip",

    "!Natural (spi)",
    "andesite", "spilitip",
    "bedrock", "spidirip",
    "coarse dirt", "spitolip",
    "clay", "spidorip",
    "diorite", "spilatip",
    "dirt", "spitalip",
    "end stone", "spidarip",
    "glowstone", "splifitip",
    "granite", "spilotip",
    "grass", "spitilip",
    "gravel", "spifatip",
    "lava", "spiratip",
    "mycelium", "spitylip",
    "netherrack", "spifotip",
    "podzol", "spitelip",
    "red sand", "spipopip",
    "red sandstone", "spipopip spip",
    "sand", "spipip",
    "sandstone", "spipip spip",
    "soul sand", "spipapip",
    "stone", "spip",
    "water", "spirotip",
    "ice", "spiretip",
    "packed ice", "spirutip",
    "blue ice", "spiritip",

    "!Stone (splu)",
    "stone bricks", "splutip",
    "cobblestone", "splupip",
    "purpur", "splurip",

    "!Utility (spla)",
    "loom", "splatorip",
    "cartography table", "splatarip",
    "smithing table", "splaterip",
    "grindstone", "splatyrip",
    "crafting table", "splatip",
    "furnace", "spladip",
    "blast furnace", "spladotip",
    "smoker", "spladatip",
    "stone cutter", "spip splatip",
    "anvil", "splabotip",
    "enchanting table", "splabatip",
    "brewing stand", "splabetip",
    "cauldron", "splaretip",
    "composter", "splaratip",
    "fletching table", "splarotip",
    "campfire", "splarutip",
    "ender chest", "splanerip",
    "chest", "splanorip",
    "beacon", "splanerip",
    "conduit", "splanurip",
    "scaffolding", "splanyrip",
    "spawner", "splanirip",
    "beehive", "splasbenip",
    "bee nest", "splasbecip",
    "bell", "splanetip",
    "lectern", "splanotip",
    "jukebox", "splanytip",

    "!Plant (splo)",
    "sapling", "splosip",
    "grass", "splorip",
    "tall grass", "stridatop splorip",
    "leaves", "splolip",
    "sea pickle", "splotip",
    "coral", "splonip",
    "coral fan", "splohip",
    "fern", "splofip",
    "large fern", "stridatop splorip",
    "bamboo", "splobip",
    "lily pad", "splopip",
    "vines", "splobubip",
    "dead bush", "splodip",
    "seagrass", "splosarip",
    "tall seagrass", "stridatop splorip",
    "kelp", "splokip",
    "farmland", "splomip",
    "grass path", "splorapip",
    "cactus", "splocip",
    "chorus", "sploharip",

    "!redstone (spr)",
    "lever", "spritip",
    "pressure plate", "sprotip",
    "button", "spratip",
    "trapped chest", "sprutip",
    "repeater", "sprodip",
    "comparator", "spridip",
    "redstone torch", "sprip",
    "noteblock", "spralip",
    "hopper", "sprohip",
    "dispenser", "sprahip",
    "observer", "sprytip",
    "dropper", "sprihip",
    "piston", "sprolip",
    "sticky piston", "sprulip",
    "daylight detector", "spretip",
    "tripwire", "sprytepip",
    "redstone lamp", "spralip",

    "!Shape (spli)",
    "stair", "splitip",
    "slab", "splidip",
    "wall", "splirip",

    "!Misc Block (sple)",
    "cobweb", "splecip",
    "snow", "splesip",
    "iron bars", "splebip",
    "glass pane", "splepip",
    "flower pot", "splefip",
    "fire", "splerip",
    "sponge", "splenip",
    "bookshelf", "splebip",
    "ladder", "splelip",
    "torch", "spletip",
    "lantern", "spletarip",
    "sea lantern", "spledorip",
    "prismarine", "spledarip",
    "end portal", "splebarip",
    "end crystal", "spleborip",
    "air", "splip",

    "!Hostile Mob (sbi)",
    "blaze", "sbitarip",
    "cave spider", "sbitorip",
    "chicken jockey", "sbitirip",
    "creeper", "sbiterip",
    "drowned", "spirotip sbip",
    "elder guardian", "sbiturip",
    "ender dragon", "sbidarip",
    "enderman", "spidirip",
    "endermite", "spidyrip",
    "evoker", "spidorip",
    "ghast", "spiderip",
    "guardian", "spihetip",
    "husk", "spihotip",
    "magma cube", "spihatip",
    "phantom", "spihetip",
    "pillager", "spihutip",
    "ravager", "spihytip",
    "shulker", "spibolip",
    "silverfish", "spibalip",
    "skeleton", "spitip",
    "slime", "spibelip",
    "spider", "spiderip",
    "stray", "spibulip",
    "vex", "spibelip",
    "vindicator", "spibylip",
    "witch", "spitinip",
    "wither", "spitenip",
    "wither skeleton", "sptenip spitip",
    "zombie", "sbip",
    "zombie pigman", "spitonip",
    "zombie villager", "sbip sbebolip",

    "!Farm (sbe)",
    "bee", "sbebip",
    "chicken", "sbeckip",
    "cow", "sbecip",
    "horse (donkey, mule)", "sbehip",
    "iron golem", "slifip sbedip",
    "mooshroom", "stomip sbecip",
    "pig", "sbepip",
    "rabbit", "sberip",
    "sheep", "sbesip",
    "snow golem", "splesip sbedip",
    "villager", "sbebolip",
    "wandering trader", "spebalip",

    "!Profession (sbla)",
    "nitwit", "sbladerip",
    "unemployed", "spladarip",
    "armorer", "spladirip",
    "butcher", "spladorip",
    "cartographer", "splamenip",
    "cleric", "splamonip",
    "farmer", "splamunip",
    "fisherman", "splaminip",
    "fletcher", "splamedip",
    "leatherworker", "splamodip",
    "librarian", "splamudip",
    "mason", "splamidip",
    "shepherd", "splamydip",
    "toolsmith", "splaremip",
    "weaponsmith", "splaromip",
    "novice", "sblatatip",
    "apprentice", "sblatetip",
    "journeyman", "sblatitip",
    "expert", "sblatotip",
    "master", "sblatytip",

    "!Passive Mob (sbo)",
    "bat", "sbobip",
    "cat", "spocip",
    "fox", "spofip",
    "llama", "spolip",
    "ocelot", "spotip",
    "panda", "spopanip",
    "parrot", "spoparip",
    "polar bear", "spopabip",
    "skeleton horse", "sposahip",
    "squid", "spocip",
    "wolf", "sporip",

    "!Sea Mob (sbu)",
    "cod (fish)", "sbucip",
    "dolphin", "sbudip",
    "pufferfish", "sbupip",
    "salmon", "sbusip",
    "tropical fish", "sbutofip",
    "turtle", "sbutip",


    "!Entity (sba)",
    "item frame", "sbafip",
    "minecart", "sbamip",
    "armor stand", "sbasip",
    "painting", "sbapip",
    "dragon fireball", "sbadip",
    "shulker bullet", "sbasobip",

    "!Edible (sti)",
    "apple", "stilapip",
    "beetroot", "stibip",
    "carrot", "sticip",
    "chorus", "stichip",
    "honey", "stihip",
    "kelp", "stikip",
    "melon", "stimip",
    "melon block", "stimip slip",
    "plant", "stipip",
    "potato", "stipotip",
    "poisonous potato", "stipopotip",
    "pumpkin", "stipupip",
    "sweet berries", "stisip",
    "wheat", "stihetip",

    "!Inedible Food (sto)",
    "sugar cane", "stosip stipip",
    "sugar", "stosip",
    "honey comb", "stohip",
    "egg", "stodip",
    "cocoa bean", "stocip",
    "mushroom", "stomip",
    "nether wart", "stonip",
    "seed", "stotip",

    "!Crafted Food (ste)",
    "cookie", "stekip",
    "cake", "stecip",
    "pumpkin pie", "stepip",
    "soup", "stesip",
    "bread", "stebip",

    "!Options (scid)",
    "options", "scidip"
];

function parseWords(wordSet) {
    let categories = [];
    let catNames=[];
    let subcatNames=[];
    let subCategories = [];
    let index = 0;
    let wordList = [];
    let i = 0;
    for (; i < wordSet.length; i++) {
        if (wordSet[i].charAt(0) == "!") {
            if (wordSet[i].charAt(1) == "!") {
                categories.push(index);
                catNames.push(wordSet[i].substring(2));
            }
            else {
                subCategories.push(index);
                subcatNames.push(wordSet[i].substring(1));
            }
        }
        else {
            wordList.push(wordSet[i]);
            index++;
        }
    }
    return { words: wordList, cat: categories, subcat: subCategories,catNames:catNames,subcatNames:subcatNames};
}